services:
  linux-learning:
    build:
      context: .
      dockerfile: Dockerfile.4th
    container_name: linux_study_server
    restart: always
    volumes:
      - ./workspace:/workspace
    ports:
      - "8888:8888"
      - "2222:22"
    environment:
      - JUPYTER_TOKEN=BDBD_token
      
